name: baasbox
version: 0.0.2
author: Giovanni Laquidara <glaquidara@gmail.com>
description: BaasBox-Dart-SDK
homepage: https://github.com/joaobiriba/baasbox-dart-sdk
dev_dependencies:
  unittest: any
  browser: any